### ISSUE TITLE
Signed authenticate request succeeds after DUO_EXPIRE (5 mins) interval has passed

### ISSUE THREAD

**Issue by PolishchukOleksiy** [duosecurity/duo_dotnet#4]
Hi,
I create the sig_request for the duo iframe with the DUO_EXPIRE set to 5 minutes. I tried clicking "Send Me a Push" 6, 12 or even 25 minutes later and always get the successful authenticate response. The expiration time of the duo part in the respponse is always "time of 'send me a push click'" + ~1-1.5 minutes.
The sig_request is formed using DateTime.UtcNow
https://github.com/duosecurity/duo_dotnet/blob/aaf3f3734253f2d616850ca2ad0f88e51960bb6a/DuoWeb/DuoWeb.cs#L57

Am I missing something?

Thank You

**Comment by adrikim** [comment]
Hey there @PolishchukOleksiy,

You're looking for `APP_EXPIRE` to set the time-to-2FA limit for the end user. `APP_EXPIRE` is by default set to 1 hour:
https://github.com/duosecurity/duo_dotnet/blob/aaf3f3734253f2d616850ca2ad0f88e51960bb6a/DuoWeb/DuoWeb.cs#L26
...which is why you were able to complete a push even up to 25 minutes after. It gets included in `app_sig` here, much like `duo_sig` right above it, when the iframe initializes:
https://github.com/duosecurity/duo_dotnet/blob/aaf3f3734253f2d616850ca2ad0f88e51960bb6a/DuoWeb/DuoWeb.cs#L77

`DUO_EXPIRE` is used more on our end to make sure we receive a request from your application in a timely manner that'll prevent a replay attack ([this link](https://securitycommunity.tcs.com/infosecsoapbox/articles/2017/01/05/cookie-hijacking-learning-through-replay-attack-examples) has a decent explanation of what a replay attack is and how timestamps help in this situation). Basically, `DUO_EXPIRE` being 5 minutes long means that your browser has 5 minutes to load the Duo iframe; after that, your user has an hour to 2FA.

Closing this for now, but feel free to re-open or ask any further questions. Hope that helps, and thanks for using Duo!
